name: 'XCAudit'
description: 'Xcode logs formatter for GitHub Actions'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - name: download and install xcaudit
      run: |
        curl -sL "https://github.com/Alexander-Ignition/XCAudit/releases/download/0.1.2/xcaudit-mac.zip" | tar zx
        install xcaudit /usr/local/bin
      working-directory: ${{ github.action_path }}
      shell: bash
