name: 'XCAudit'
description: 'Xcode logs formatter for GitHub Actions'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - name: install xcaudit
      run: install ./Products/xcaudit /usr/local/bin
      working-directory: ${{ github.action_path }}
      shell: bash
