name: 'XCAudit'
description: 'Xcode logs formatter for GitHub Actions'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - name: build and install xcaudit
      run: |
        TAG=$(git describe --tags --abbrev=0)
        curl -sL "https://github.com/Alexander-Ignition/XCAudit/releases/download/$TAG/xcaudit-mac.zip" | tar zx
        install xcaudit /usr/local/bin
      working-directory: ${{ github.action_path }}
      shell: bash
