name: 'XCAudit'
description: 'Xcode logs formatter for GitHub Actions'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - name: build and install xcaudit
      run: |
        swift build -c release --disable-sandbox
        install "$(swift build -c release --show-bin-path)/xcaudit" /usr/local/bin
      working-directory: ${{ github.action_path }}
      shell: bash
