name: Build
on: workflow_dispatch

jobs:
  test:
    name: Run build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Toolchain
        run: |
          xcodebuild -version
          swift build --version
        shell: bash
      - name: Build universal binary
        id: build
        run: | 
          swift_build="swift build -c release --disable-sandbox --arch arm64 --arch x86_64"
          $swift_build
          bin_path=$($swift_build --show-bin-path)  
          echo "::set-output name=bin_path::$bin_path/xcaudit"
        shell: bash
      - name: Binary info
        run: lipo -info ${{ steps.build.outputs.bin_path }}
        shell: bash
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: xcaudit
          path: ${{ steps.build.outputs.bin_path }}
